### PR TITLE
Remove needless line

### PR DESCRIPTION
**Pull request by marci543**
I think that line is not necessary.

Many thanks for the image.

### CODE REVIEW

**Comment by marci543** [comment]
@bergkvist
Can you please add this small change if appropriate?

By the way the new [v4.0.0draft5](https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v4.0.0draft5) is released.

**Comment by bergkvist** [comment]
Looks good! Okay, thanks - I'll look into publishing v4.0.0draft5 now :)

**Comment by bergkvist** [comment]
v4.0.0draft5 is published now: https://hub.docker.com/r/graphblas/graphblas

Note that the compiled shared library is around 4x bigger than the previous version. (448MB uncompressed vs 109MB)

I guess this significant size increase might have something to do with the CUDA support (https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v4.0.0draft5)

**Comment by marci543** [comment]
Thank you for the release. It might be useful to ask Tim Davis about the issue.

**Comment by bergkvist** [comment]
Yeah, seems like it might be because debug mode is enabled:
https://github.com/DrTimothyAldenDavis/GraphBLAS/issues/18

**Pull request merged**
